spring.application.name=health-alert-engine
server.port=9097

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.streams.application-id=health-alert-engine
spring.kafka.streams.properties.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.default.value.serde=org.springframework.kafka.support.serializer.JsonSerde
spring.kafka.streams.properties.spring.json.trusted.packages=*

wearable.topic.raw=wearable.telemetry.raw
alert.topic.patient=health.alerts.patient
alert.topic.doctor=health.alerts.doctor

patient.service.url=http://patient-service:9091
