spring.application.name=ingest-wearables-service
server.port=9096

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.type.mapping=wearableMetricEvent:com.upec.episantecommon.event.WearableMetricEvent

# Topic names
ingest.wearable.topic=wearable.telemetry.raw

# Actuator
management.endpoints.web.exposure.include=health,prometheus
